import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
BIOINFO_ROOT = os.getenv('BIOINFO_ROOT')
SNAKE_ROOT=os.getenv('SNAKE_ROOT')

BIN_DIR=PRJ_ROOT+"/local/bin"
SRC_DIR=PRJ_ROOT+"/local/src"

#PHIX=PRJ_ROOT+'/local/share/data/phix/phiX'
PHIX='/mnt/trcanmed/snaketree/prj/cellecta_barcode/local/share/data/phix/phiX'
FQ_DIR=PRJ_ROOT+"/local/share/data/220706_M02679_0327_000000000-GD2G4/Data/Intensities/BaseCalls/"
#SAMPLES_ORIG=["322_A","322_B","322_E","322_F","322_G","322_H","322_I","322_J","322_K","322_L"]

#SAMPLES=["basale_1","basale_2","basale_3","vitro_1", "vitro_2","vitro_3","topo_1", "topo_3","topo_4","topo_5"]

#egrassi@godot:/mnt/trcanmed/snaketree/prj/cellecta_barcode/local/share/data/nextseq_larger_dec2021$ ls org_xeno_livermet_327_* | sed 's/\.fastq\.gz/"/' | sed 's/^/"/' | tr "\n" ","
SAMPLES=["xeno-livermet-CRC1307-55C-9c_S3_L001","xeno-livermet-CRC1307-55C-9_S1_L001","xeno-livermet-CRC1307-58C-9c_S4_L001","xeno-livermet-CRC1307-58C-9_S2_L001", "Undetermined_S0_L001"]
CORES=4
